// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjsOhDJwOFFTSfu6iBr3_2wmr_u3_f6w',
    appId: '1:537006887243:web:5b34f51a894e92ddf358ce',
    messagingSenderId: '537006887243',
    projectId: 'winter-arc-e143c',
    authDomain: 'winter-arc-e143c.firebaseapp.com',
    storageBucket: 'winter-arc-e143c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVakvwnhBcliwi7wmfPG7WHcmlexUlLQ',
    appId: '1:537006887243:android:bbbc965f278cb143f358ce',
    messagingSenderId: '537006887243',
    projectId: 'winter-arc-e143c',
    storageBucket: 'winter-arc-e143c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu8dNGYFk2bf72pbs0tA-b13DRpYFHrec',
    appId: '1:537006887243:ios:c68918058e9da625f358ce',
    messagingSenderId: '537006887243',
    projectId: 'winter-arc-e143c',
    storageBucket: 'winter-arc-e143c.firebasestorage.app',
    iosBundleId: 'com.example.winterArc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu8dNGYFk2bf72pbs0tA-b13DRpYFHrec',
    appId: '1:537006887243:ios:c68918058e9da625f358ce',
    messagingSenderId: '537006887243',
    projectId: 'winter-arc-e143c',
    storageBucket: 'winter-arc-e143c.firebasestorage.app',
    iosBundleId: 'com.example.winterArc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfjsOhDJwOFFTSfu6iBr3_2wmr_u3_f6w',
    appId: '1:537006887243:web:0024ebc3de166f75f358ce',
    messagingSenderId: '537006887243',
    projectId: 'winter-arc-e143c',
    authDomain: 'winter-arc-e143c.firebaseapp.com',
    storageBucket: 'winter-arc-e143c.firebasestorage.app',
  );
}
